//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.20 at 08:08:18 PM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://metrics.sourceforge.net/2003/Metrics-First-Flat", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package schema.metrics2;
