/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TreeViewerUI_.java
 *
 * Created on 29/03/2011, 22:41:12
 */

package com.tesis.aether.examples.tree.viewer.common.ui;

import com.tesis.aether.examples.tree.viewer.common.TreeFileViewer;
import com.tesis.aether.examples.tree.viewer.common.TreeLoader;
import java.io.File;
import java.io.IOException;
import java.util.Properties;

/**
 *
 * @author Marcos
 */
public abstract class TreeViewerUI extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private Properties properties = new Properties();
    protected String accessKey = "tree.viewer.accessKey";
    protected String secretKey = "tree.viewer.secretKey";
    private TreeLoader treeLoader = null;

    /** Creates new form TreeViewerUI_ */
    public TreeViewerUI() {
        treeLoader = new TreeLoader();
        initComponents();
        try {
            properties.load(new File("properties.properties").toURI().toURL().openStream());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        getCloud().connect(properties.getProperty(accessKey), properties.getProperty(secretKey));
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBucket = new javax.swing.JTextField();
        cmdRefresh = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bucket:");

        cmdRefresh.setText("Refresh");
        cmdRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRefreshActionPerformed(evt);
            }
        });

        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeLoader.gerRoot()));
        jScrollPane1.setViewportView(tree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBucket, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdRefresh)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBucket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRefreshActionPerformed
        try {
            treeLoader = getCloud().loadFileTree(txtBucket.getText(), properties.getProperty(accessKey), properties.getProperty(secretKey));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeLoader.gerRoot()));
        tree.updateUI();
    }//GEN-LAST:event_cmdRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cmdRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree tree;
    private javax.swing.JTextField txtBucket;
    // End of variables declaration//GEN-END:variables
    protected abstract TreeFileViewer getCloud();

}
