//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.20 at 05:42:50 PM ART 
//


package schema.mylyn;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InteractionEvent" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Delta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Interest" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Kind" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Navigation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="OriginId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="StructureHandle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="StructureKind" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="NumEvents" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CreationCount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interactionEvent"
})
@XmlRootElement(name = "InteractionHistory")
public class InteractionHistory {

    @XmlElement(name = "InteractionEvent")
    protected List<InteractionHistory.InteractionEvent> interactionEvent;
    @XmlAttribute(name = "Id")
    protected String id;
    @XmlAttribute(name = "Version")
    protected String version;

    /**
     * Gets the value of the interactionEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interactionEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInteractionEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InteractionHistory.InteractionEvent }
     * 
     * 
     */
    public List<InteractionHistory.InteractionEvent> getInteractionEvent() {
        if (interactionEvent == null) {
            interactionEvent = new ArrayList<InteractionHistory.InteractionEvent>();
        }
        return this.interactionEvent;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Delta" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Interest" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Kind" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Navigation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OriginId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="StructureHandle" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="StructureKind" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="NumEvents" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CreationCount" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class InteractionEvent {

        @XmlAttribute(name = "Delta")
        protected String delta;
        @XmlAttribute(name = "EndDate")
        protected String endDate;
        @XmlAttribute(name = "Interest")
        protected String interest;
        @XmlAttribute(name = "Kind")
        protected String kind;
        @XmlAttribute(name = "Navigation")
        protected String navigation;
        @XmlAttribute(name = "OriginId")
        protected String originId;
        @XmlAttribute(name = "StartDate")
        protected String startDate;
        @XmlAttribute(name = "StructureHandle")
        protected String structureHandle;
        @XmlAttribute(name = "StructureKind")
        protected String structureKind;
        @XmlAttribute(name = "NumEvents")
        protected String numEvents;
        @XmlAttribute(name = "CreationCount")
        protected String creationCount;

        /**
         * Gets the value of the delta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDelta() {
            return delta;
        }

        /**
         * Sets the value of the delta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDelta(String value) {
            this.delta = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndDate(String value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the interest property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterest() {
            return interest;
        }

        /**
         * Sets the value of the interest property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterest(String value) {
            this.interest = value;
        }

        /**
         * Gets the value of the kind property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKind() {
            return kind;
        }

        /**
         * Sets the value of the kind property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKind(String value) {
            this.kind = value;
        }

        /**
         * Gets the value of the navigation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNavigation() {
            return navigation;
        }

        /**
         * Sets the value of the navigation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNavigation(String value) {
            this.navigation = value;
        }

        /**
         * Gets the value of the originId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginId() {
            return originId;
        }

        /**
         * Sets the value of the originId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginId(String value) {
            this.originId = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartDate(String value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the structureHandle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStructureHandle() {
            return structureHandle;
        }

        /**
         * Sets the value of the structureHandle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStructureHandle(String value) {
            this.structureHandle = value;
        }

        /**
         * Gets the value of the structureKind property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStructureKind() {
            return structureKind;
        }

        /**
         * Sets the value of the structureKind property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStructureKind(String value) {
            this.structureKind = value;
        }

        /**
         * Gets the value of the numEvents property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumEvents() {
            return numEvents;
        }

        /**
         * Sets the value of the numEvents property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumEvents(String value) {
            this.numEvents = value;
        }

        /**
         * Gets the value of the creationCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreationCount() {
            return creationCount;
        }

        /**
         * Sets the value of the creationCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreationCount(String value) {
            this.creationCount = value;
        }

    }

}
