//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.20 at 08:08:18 PM ART 
//


package schema.metrics2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Metric" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://metrics.sourceforge.net/2003/Metrics-First-Flat}Value" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Values" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://metrics.sourceforge.net/2003/Metrics-First-Flat}Value" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="per" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="avg" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="stddev" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="maxinrange" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="hint" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="scope" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metric"
})
@XmlRootElement(name = "Metrics")
public class Metrics {

    @XmlElement(name = "Metric")
    protected List<Metrics.Metric> metric;
    @XmlAttribute(name = "scope")
    protected String scope;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "date")
    protected String date;

    /**
     * Gets the value of the metric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Metrics.Metric }
     * 
     * 
     */
    public List<Metrics.Metric> getMetric() {
        if (metric == null) {
            metric = new ArrayList<Metrics.Metric>();
        }
        return this.metric;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://metrics.sourceforge.net/2003/Metrics-First-Flat}Value" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Values" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://metrics.sourceforge.net/2003/Metrics-First-Flat}Value" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="per" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="avg" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="stddev" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="maxinrange" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="hint" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value",
        "values"
    })
    public static class Metric {

        @XmlElement(name = "Value")
        protected List<Value> value;
        @XmlElement(name = "Values")
        protected List<Metrics.Metric.Values> values;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "description")
        protected String description;
        @XmlAttribute(name = "max")
        protected String max;
        @XmlAttribute(name = "hint")
        protected String hint;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Value }
         * 
         * 
         */
        public List<Value> getValue() {
            if (value == null) {
                value = new ArrayList<Value>();
            }
            return this.value;
        }

        /**
         * Gets the value of the values property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the values property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValues().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Metrics.Metric.Values }
         * 
         * 
         */
        public List<Metrics.Metric.Values> getValues() {
            if (values == null) {
                values = new ArrayList<Metrics.Metric.Values>();
            }
            return this.values;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the max property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMax(String value) {
            this.max = value;
        }

        /**
         * Gets the value of the hint property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHint() {
            return hint;
        }

        /**
         * Sets the value of the hint property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHint(String value) {
            this.hint = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://metrics.sourceforge.net/2003/Metrics-First-Flat}Value" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="per" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="avg" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="stddev" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="maxinrange" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Values {

            @XmlElement(name = "Value")
            protected List<Value> value;
            @XmlAttribute(name = "per")
            protected String per;
            @XmlAttribute(name = "avg")
            protected String avg;
            @XmlAttribute(name = "stddev")
            protected String stddev;
            @XmlAttribute(name = "max")
            protected String max;
            @XmlAttribute(name = "maxinrange")
            protected String maxinrange;
            @XmlAttribute(name = "total")
            protected String total;

            /**
             * Gets the value of the value property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the value property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getValue().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Value }
             * 
             * 
             */
            public List<Value> getValue() {
                if (value == null) {
                    value = new ArrayList<Value>();
                }
                return this.value;
            }

            /**
             * Gets the value of the per property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPer() {
                return per;
            }

            /**
             * Sets the value of the per property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPer(String value) {
                this.per = value;
            }

            /**
             * Gets the value of the avg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAvg() {
                return avg;
            }

            /**
             * Sets the value of the avg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAvg(String value) {
                this.avg = value;
            }

            /**
             * Gets the value of the stddev property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStddev() {
                return stddev;
            }

            /**
             * Sets the value of the stddev property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStddev(String value) {
                this.stddev = value;
            }

            /**
             * Gets the value of the max property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMax() {
                return max;
            }

            /**
             * Sets the value of the max property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMax(String value) {
                this.max = value;
            }

            /**
             * Gets the value of the maxinrange property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxinrange() {
                return maxinrange;
            }

            /**
             * Sets the value of the maxinrange property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxinrange(String value) {
                this.maxinrange = value;
            }

            /**
             * Gets the value of the total property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotal() {
                return total;
            }

            /**
             * Sets the value of the total property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotal(String value) {
                this.total = value;
            }

        }

    }

}
